version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend/interactEM"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "swelborn"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
