# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: sync-readmes
        name: sync-readmes
        entry: uv run --project docs/ docs/scripts/sync_readmes.py
        language: system
        pass_filenames: false
        files: ^(docs/|README.md|operators/README\.md|backend/agent/README\.md)
